[relaychain]
default_command = "../polkadot-sdk/target/release/polkadot"
default_args = [ "-lparachain=debug" ]
chain = "rococo-local"

[[relaychain.nodes]]
name = "alice"
validator = true
rpc_port = 9922
args = [
	"--enable-offchain-indexing=true", "--pruning=archive",
]

[[relaychain.nodes]]
name = "bob"
validator = true

[[relaychain.nodes]]
name = "charlie"
validator = true

[[relaychain.nodes]]
name = "dave"
validator = true

[[parachains]]
id = 2000
chain = "gargantua-2000"
cumulus_based = true


[[parachains.collators]]
name = "alice"
rpc_port = 9990
command = "./target/release/hyperbridge"
args = [
	"-lbasic-authorship=trace,ismp=trace,xcm=trace"]


[[parachains.collators]]
name = "bob"
rpc_port = 9991
command = "./target/release/hyperbridge"
suri = "//Bob"
args = ["-lparachain=debug"]

# run charlie as parachain collator
[[parachains.collators]]
name = "charlie"
rpc_port = 9992
command = "./target/release/hyperbridge"
suri = "//Charlie"
args = ["-lparachain=debug"]

[[parachains.collators]]
name = "dave"
command = "./target/release/hyperbridge"
rpc_port = 9993
suri = "//Dave"
args = ["-lparachain=debug,aura=debug"]







